import type { ThemeConfig } from 'antd';

const lightTheme: ThemeConfig = {
  token: {
    colorPrimary: '#1677ff',
    colorSuccess: '#52c41a',
    colorWarning: '#faad14',
    colorError: '#ff4d4f',
    colorInfo: '#1677ff',
    colorBgBase: '#ffffff',
    colorTextBase: '#000000',
    fontSize: 14,
    fontFamily:
      "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
    borderRadius: 6,
    borderRadiusSM: 4,
    borderRadiusLG: 8,
    borderRadiusXS: 2,
    wireframe: false,
    controlHeight: 32,
    controlHeightSM: 24,
    controlHeightLG: 40,
    sizeStep: 4,
    sizeUnit: 4,
    colorLink: '#1677ff',
    colorLinkHover: '#69b1ff',
    colorLinkActive: '#0958d9',
  },
  components: {
    Layout: {
      siderBg: '#001529',
      headerBg: '#ffffff',
      bodyBg: '#f5f5f5',
      headerHeight: 64,
      headerPadding: '0 24px',
      headerColor: 'rgba(0, 0, 0, 0.88)',
    },
    Menu: {
      darkItemBg: '#001529',
      darkSubMenuItemBg: '#000c17',
      darkPopupBg: '#001529',
      darkGroupTitleColor: 'rgba(255, 255, 255, 0.45)',
      darkItemColor: 'rgba(255, 255, 255, 0.65)',
      darkItemHoverBg: 'transparent',
      darkItemHoverColor: '#ffffff',
      darkItemSelectedBg: '#1677ff',
      darkItemSelectedColor: '#ffffff',
      itemBg: '#ffffff',
      itemColor: 'rgba(0, 0, 0, 0.88)',
      itemHoverBg: '#f5f5f5',
      itemHoverColor: '#1677ff',
      itemSelectedBg: '#e6f4ff',
      itemSelectedColor: '#1677ff',
      itemActiveBg: '#e6f4ff',
      groupTitleColor: 'rgba(0, 0, 0, 0.45)',
      groupTitleFontSize: 14,
      itemBorderRadius: 6,
      subMenuItemBorderRadius: 6,
      iconSize: 14,
      collapsedIconSize: 16,
      collapsedWidth: 80,
      itemHeight: 40,
      itemMarginInline: 4,
      itemMarginBlock: 4,
      popupBg: '#ffffff',
    },
  },
};

export default lightTheme;
